In [ ]:
#pandas

In [ ]:
!pip install pandas

In [ ]:
!pip install pandas numpy

In [7]:
import pandas as pd
import numpy as np

data = {"Name": ["Ankit", "Rahul","mukesh","sanju","printam","pankaj","niraj"], "Age": [21, 22,23,34,28,30,40],
       "salary":[1000,2000,3000,4000,5000,6000,7000]
       
       
       
       
       }

df = pd.DataFrame(data)
print(df)

      Name  Age  salary
0    Ankit   21    1000
1    Rahul   22    2000
2   mukesh   23    3000
3    sanju   34    4000
4  printam   28    5000
5   pankaj   30    6000
6    niraj   40    7000

In [3]:
df.head(3)

     Name  Age  salary
0   Ankit   21    1000
1   Rahul   22    2000
2  mukesh   23    3000

In [5]:
df.tail(2)

     Name  Age  salary
5  pankaj   30    6000
6   niraj   40    7000

In [11]:
df.columns

Index(['Name', 'Age'], dtype='str')

In [14]:
df.Age

0    21
1    22
2    23
3    34
4    28
5    30
6    40
Name: Age, dtype: int64

In [15]:
df.Name

0      Ankit
1      Rahul
2     mukesh
3      sanju
4    printam
5     pankaj
6      niraj
Name: Name, dtype: str

In [18]:
df.salary

0    1000
1    2000
2    3000
3    4000
4    5000
5    6000
6    7000
Name: salary, dtype: int64

In [19]:
df.salary.sum()

np.int64(28000)

In [21]:
df.salary.min()

np.int64(1000)

In [22]:
df.salary.max()

np.int64(7000)

In [23]:
df.salary.mean()

np.float64(4000.0)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     7 non-null      int64
 2   salary  7 non-null      int64
dtypes: int64(2), str(1)
memory usage: 300.0 bytes

In [25]:
df.describe()

             Age       salary
count   7.000000     7.000000
mean   28.285714  4000.000000
std     6.993194  2160.246899
min    21.000000  1000.000000
25%    22.500000  2500.000000
50%    28.000000  4000.000000
75%    32.000000  5500.000000
max    40.000000  7000.000000

In [8]:
df.shape

(7, 3)

In [13]:

data = {"Name": ["Ankit", np.nan,"mukesh",np.nan,"printam","pankaj","niraj"],
        "Age": [21, 22,23,np.nan,28,30,np.nan],
       "salary":[1000,np.nan,3000,4000,np.nan,6000,7000]
       }

In [14]:
df = pd.DataFrame(data)

In [15]:
df

      Name   Age  salary
0    Ankit  21.0  1000.0
1      NaN  22.0     NaN
2   mukesh  23.0  3000.0
3      NaN   NaN  4000.0
4  printam  28.0     NaN
5   pankaj  30.0  6000.0
6    niraj   NaN  7000.0

In [16]:
df.isnull()

    Name    Age  salary
0  False  False   False
1   True  False    True
2  False  False   False
3   True   True   False
4  False  False    True
5  False  False   False
6  False   True   False

In [17]:
df.isnull().sum()

Name      2
Age       2
salary    2
dtype: int64

In [18]:
df.isnull().sum().sum()

np.int64(6)

In [19]:
print(df.isnull().sum().sum())

6

In [20]:
# remove all null values
df.dropna()

     Name   Age  salary
0   Ankit  21.0  1000.0
2  mukesh  23.0  3000.0
5  pankaj  30.0  6000.0

In [29]:
#replace missing value witha dummy value
df.fillna(value="missing")

      Name      Age   salary
0    Ankit     21.0   1000.0
1  missing     22.0  missing
2   mukesh     23.0   3000.0
3  missing  missing   4000.0
4  printam     28.0  missing
5   pankaj     30.0   6000.0
6    niraj  missing   7000.0

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      float64
 2   salary  5 non-null      float64
dtypes: float64(2), str(1)
memory usage: 300.0 bytes

In [ ]:
newdf = df.copy()

In [37]:
newdf

      Name      Age   salary
0    Ankit     21.0   1000.0
1  missing     22.0  missing
2   mukesh     23.0   3000.0
3  missing  missing   4000.0
4  printam     28.0  missing
5   pankaj     30.0   6000.0
6    niraj  missing   7000.0

In [43]:
df['Name'] = df['Age'].fillna('missing')

In [44]:
df

      Name   Age  salary
0     21.0  21.0  1000.0
1     22.0  22.0  4200.0
2     23.0  23.0  3000.0
3  missing   NaN  4000.0
4     28.0  28.0  4200.0
5     30.0  30.0  6000.0
6  missing   NaN  7000.0

In [46]:
df['salary'] = df['salary'].fillna(value = df['salary'].mean())

In [47]:
df

      Name   Age  salary
0     21.0  21.0  1000.0
1     22.0  22.0  4200.0
2     23.0  23.0  3000.0
3  missing   NaN  4000.0
4     28.0  28.0  4200.0
5     30.0  30.0  6000.0
6  missing   NaN  7000.0